through - через, сквозь
rare - редкий
arrange - организовывать
explicitly - в явном виде
passed - прошло
weak - слабый
worst - худший
instead - вместо 
behave - вести себя
convention - условность
prepended - указывая префикс
whereas - в то время как
invoked - вызываться
raw - сырье
relevant - соответствующий
offending - оскорбительный
treat - рассматривать
trunk - магистраль
purpose - цель
aware - осведомлённый
either - или 
confused - смущенный
establishment - создание
probe - зонд
frequently - часто
wordy - многословный
commonly - обычно
avoid - избежать
due - в связи
obvious - очевидный 
stick - придерживаться
pruning - сокращение
rely - полагаться
attempts - попытки
exceeded - превышено
increase - увеличение
case - случай 
conclude - заключать
afterwards - потом
evade - уклоняться
dedicated - преданный 
provision - обеспечение 
least - наименее 
entire - все
thoughts - мысли 
obtain - получать 
rather - скорее
precision - точность 
whole - целый
entry - запись
declare - объявлять
restrain - ограничивать
initial - начальная 
describing - описывающее 
backticks - кавычка
deprecated - выступать против
nest - гнездо
environments - окружение
complicated - сложно
submitting - предосталвение
grab - захват
abandons - отказываться от
probability - вероятность
suggestion - предложение
reveal - выявить
implied - подразумеваемый
conveying - выражать
deploy - развертывание
amount - количество
reduced - уменьшенный
terse - краткий
descend - спускаться
assuming - предпологая
inconvenience - неудобство
cause - причина
drawback - недостаток
demand - спрос
impact - влияние
mandatory - обязательное
wrap - заворачивать
determine - определить
further - далее
necessary - необходимо
retrieved - извлекаться
satisfy - удовлетворять
benefit - выгода
rude - грубый
expensive - дорогая
pace - темп
responsive - отзывчивый
pretend - делать вид
occasion - повод 
retarded - замедленный
threat - угроза
expand - расширять
anchor - якорь
except - исключая
outstanding - выдающийся
towards - в направлении
ensure - гарантировать
opportunity - возможность
probaly - вероятно
respond - отвечать
involved - участвует
consumption - потребление
contribute - делать вклад
solve - решать
suddenly - внезапно
urgently - срочно
instant - мгновенное
instance - пример
hence - следовательно
essential - основной
branche - ветвь
commit - совершить
definitive - окончательный
merged - слиты
accomplish - выполнять
consider - рассматривать
prefer - предпочитать
related - связанный
during - во время
allow - позволять
unleash - развязать
queue - очередь
query - запрос
enhance - усилить
confined - ограниченный
conventional - обычный
fetch - выборка
simultaneously - одновременно
awful - ужасный
fabulous - невероятный
vague - расплывчатый
gain - прирост
approach - подход
performe - выполнять
reliably - надежно
refers - относится
malicious - вредоносная
forgery - подлог
performing - выполнение
comprehensive - комплексный
facilities - оборудование
comprises - включает
exhaustive - исчерпывающий
aim - цель
harness - жгут
debt - долг
reflects - отражает
arises - возникает
vulnerability - уязвимость
heaven - небеса
encourage - поощрять
invent - выдумывать
billable - оплачиваемые
evaluate - оценивать
prevent - предотвращение
involvement - участие
struggle - борьба
embedded - внедренной
strict - строгий
intended - предназначено
prepare - подготовить
stagging - спекуляции
occur - происходят
maintain - поддерживать
necessity - необходимость
deterrent - сдерживание
despite - несмотря
fairly - довольно
toggle - костыль
rid - избавиться
regarding - относительно
mentioned - упомянутых
pitfalls - подводные камни
strive - стремиться
intervene - вмешиваться
distinct - отчетлевый
prohibited - запрещено
align - выравнивать
familiar - знакомые
immutable - неизменный
advantage - преимущество
statement - заявление
clue - ключ к разгадке
extensible - растяжимый
ratio - соотношение
evident - очевидный
facilitate - содействовать
advise - сообщать
promptly - быстро
scope - объём
lack - отсутствие
harm - вред
thoroughly - тщательно
assertion - утверждение
maturity - зрелость
threshold - предел
competitor - конкурент
eliminate - устранить
destiny - удел
mature - зрелый
doze - дремать
commitments - обязательства
procrastinate - мешкать
clarify - прояснить
fortnight - две недели